name: KOB Band
favicon: null
layout_spectrum: 0.6606284726876765
typography_spectrum: 0.8839353227522224
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.3745869412086904
  lightness: 0.7899373164400458
  saturation: 0.5815297143999487
  rhythmicContrast: 0.16193455317988992
purpose: []
