name: KOB Band
favicon: null
layout_spectrum: 0
typography_spectrum: 0.8839353227522224
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcfcfc'
    - '#020001'
    - '#99a39b'
    - '#666259'
    - '#80d2fe'
  brandStrength: 0.375
  lightness: 0.7899373164400458
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
